model:
  type: autoencoder
  input_dim: 29  
  encoding_dim: 14
  random_state: 42
  anomaly_threshold: 99.9

training:
  reference_data: data/processed/reference.csv
  validation_data: data/processed/validation.csv
  epochs: 50
  learning_rate: 0.001
  batch_size: 256

mlflow:
  experiment_name: fraud_detection_changeThreshold
  run_name: autoencoder_3
