global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'fastapi-model'
    static_configs:
      - targets: ['api:8000']
      #- targets: ['localhost:8000']
rule_files:
- '/etc/prometheus/alerts.yml'