global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'fastapi-model'
    static_configs:
      - targets: ['localhost:8000']
      #- targets: ['host.docker.internal:8000']